Blog/urls.py
from django.contrib import admin
from django.urls import path, include

import author.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('author.urls')),
    path('', include('article.urls')),
    path('', author.views.main)
]

author/urls.py
__author__ = "Rifiuto"
__version__ = '1.0'

from django.urls import path, include
from . import views


app_name = 'author'
# 路由级连包含
urlpatterns = [
    path('author/', include([
        path('register/', views.author_registor, name='register'),
        path('login/', views.author_login, name='login'),
    ]
    ))
]

author/models.py
import datetime
import uuid

from django.db import models
from uuid import uuid4


# Create your models here.
class Author(models.Model):
    GENDER = (
        ('0', '女'),
        ('1', '男')
    )
    STATUS = (
        ('0', "正常"),
        ('1', '锁定'),
        ('2', '删除')
    )
    # 作者编号
    # id = models.AutoField(primary_key=True, verbose_name="作者编号")
    id = models.UUIDField(primary_key=True, verbose_name="作者编号", auto_created=True, default=uuid.uuid4())
    # 登陆帐号
    username = models.CharField(max_length=50, unique=True, verbose_name="登陆帐号")
    # 登陆密码
    password = models.CharField(max_length=50, verbose_name="登陆密码")
    # 真实姓名
    realname = models.CharField(max_length=20, default="待完善", verbose_name="作者姓名",
                                null=True, blank=True, db_index=True)
    # 用户昵称
    nickname = models.CharField(max_length=20, verbose_name="作者昵称", unique=True,
                                null=True, blank=True, db_index=True)
    # 年龄
    age = models.IntegerField(default=0, verbose_name="作者年龄")
    # 性别
    gender = models.CharField(max_length=1, choices=GENDER, verbose_name="年龄",
                              null=True, blank=True)
    # 邮箱
    email = models.EmailField(max_length=20, verbose_name="联系邮箱",
                              null=True, blank=True, db_index=True)
    # 电话
    phone = models.CharField(max_length=20, verbose_name="联系电话", null=True,
                             blank=True, db_index=True)
    # 用户状态
    status = models.CharField(max_length=5, choices=STATUS, default="正常", verbose_name="用户状态", help_text="必须选择其中一个")
    # 帐号注册时间
    create_time = models.DateField(default=datetime.datetime.now, verbose_name="注册时间")
    # 帐号修改时间
    update_time = models.DateField(auto_now=True, verbose_name="修改时间")
    # 个人主页
    personal_page = models.URLField(verbose_name="个人主页", null=True, blank=True)
    # 个人介绍
    intro = models.TextField(verbose_name="个人介绍", null=True)
    # 备注信息
    remark = models.TextField(verbose_name="备注信息", null=True)

    class Meta:
        verbose_name_plural = "作者"

    def __str__(self):
        return f"帐号:{self.username} 昵称{self.nickname} 姓名{self.realname}"


class AuthorProfile(models.Model):
    '''用户拓展资料'''
    # 拓展资料编号
    id = models.UUIDField(verbose_name="作者编号", primary_key=True, auto_created=True, default=uuid4)
    # 粉丝数量
    fans_count = models.IntegerField(verbose_name="粉丝数量", default=0)
    # 访问数量
    visited_count = models.IntegerField(verbose_name="访问数量", default=0)
    # 文章字数
    words_count = models.IntegerField(verbose_name="文章字数", default=0)
    # 文章篇数
    article_count = models.IntegerField(verbose_name="文章篇数", default=0)
    # 收藏总数量
    collected_count = models.IntegerField(verbose_name="收藏总数量", default=0)
    # 喜欢总数量
    like_count = models.IntegerField(verbose_name="喜欢总数量", default=0)
    # 点赞总数量
    admired_count = models.IntegerField(verbose_name="点赞总数量", default=0)
    # 关联用户
    profile_author = models.OneToOneField(Author, on_delete=models.CASCADE)
    # 喜欢的文章
    article_liked = models.ManyToManyField('article.Article', related_name='articleLiked')
    # 收藏的文章
    article_collected = models.ManyToManyField('article.Article', related_name="articleCollected")

author/views.py
from django.shortcuts import render
from .models import Author
# Create your views here.


def author_registor(request):
    if request.method == "GET":
        return render(request, 'register.html', {})
    elif request.method == "POST":
        print(request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')
        realname = request.POST.get('realname')
        nickname = request.POST.get('nickname')
        sex = request.POST.get('sex')
        age = request.POST.get('age')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        status = request.POST.get('status')
        # print(status)
        author = Author.objects.filter(username=username)
        if len(author) > 0:
            return render(request, 'register.html', {
                'msg_code': 0,
                'msg_info': "帐号已经存在"
            })
        author = Author(username=username, password=password, realname=realname,
                        nickname=nickname, gender=sex, age=age, email=email, phone=phone,
                        status=status)
        author.save()
        return render(request, 'login.html', {
            'msg_code': 0,
            'msg_info': "帐号注册成功",
            'msg_account': username,
            'msg_title': "确认输入账户密码"
        })


def author_login(request):
    if request.method == "GET":
        return render(request, 'login.html', {
            'msg_title': "请输入账户和密码"
        })
    else:
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            author = Author.objects.get(username=username, password=password)
            print(type(author))
            request.session['author'] = author
            return render(request, 'index.html', {
                'msg_code': 0,
                'msg_info': "登陆成功",
            })
        except:
            return render(request, 'login.html', {
                'msg_code': -1,
                'msg_info': "帐号或者密码出现问题，请重新登陆"
            })


def main(request):
    return render(request, 'main.html')

author/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户首页</title>
</head>
<body>
<h2>用户信息展示</h2>
<div>
    <h3>当前登陆用户帐号：{{ request.session.author.username }}</h3>
    <h3>当前登陆用户姓名：{{ request.session.author.realname }}</h3>
</div>
</body>
</html>

author/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户登陆</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-4.6.1-dist/css/bootstrap.css' %}">
</head>
<body>
<h2 class="text-center">用户登陆</h2>
<h3 class="error_msg">{{ msg_info }}</h3>
<form action="{% url 'author:login' %}" method="post">
    {% csrf_token %}
    <div class="card text-center">
        <div class="card-header">
            <h4>{{ msg_title }}</h4>
        </div>
        <div class="card-body align-items-center">
            <form action="POST">
                <div class="form-group col-md-6">
                    <input class="form-control" type="text" name="username" id="username" value="{{ msg_account }}">
                </div>
                <div class="form-group col-md-6">
                    <input class="form-control" type="password" name="password" id="password">
                </div>
                <input type="submit" class="btn btn-dark" value="立即登陆">
            </form>
        </div>
    </div>

</form>
</body>
</html>

author/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main Page</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-4.6.1-dist/css/bootstrap.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">My Own web</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">博客首页 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">我的主页</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled">我的私信</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled">发表文章</a>
      </li>
    </ul>
    <form class="form-inline">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
  <ul class="navbar-nav mr-auto">
      <li>
          <a href="author/register/" class="nav-link">注册</a>
      </li>
      <li>
          <a href="author/login/" class="nav-link">登陆</a>
      </li>
  <ul/>

</nav>
<ins>can you help me</ins>
<br/>
<u>can you help me</u>
<script src="{% static 'plugins/jQuery/jquery-3.6.0.js' %}"></script>
</body>
</html>

author/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户注册</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-4.6.1-dist/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/one.css' %}">
</head>
<body>

<h3 class="error_msg">{{ msg_info }}</h3>
<div class="container col-4" style="text-align: center; padding: 100px 0;">
    <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#staticBackdrop">
  Launch static backdrop modal
</button>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Understood</button>
      </div>
    </div>
  </div>
</div>
    <div class="card align-items-center justify-content-center">
        <div class="card-header col-md-8">
            <h2>新用户注册</h2>
        </div>
        <div class="card-body">
            <form id="register_form" action="{% url 'author:register' %}" method="post">
                {% csrf_token %}
                <div id="one" class="form-group row">
                    <label for="username" class="col-form-label">帐号</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" name="username" id="username" placeholder="请输入帐号">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="password" class="col-form-label">密码</label>
                    <div class="col-md-8">
                        <input type="password" class="form-control" name="password" id="password" placeholder="请输入密码">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="realname" class="col-form-label">姓名</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" name="realname" id="realname" placeholder="请输入姓名">
                    </div>

                </div>
                <div class="form-group row">
                    <label for="nickname" class="col-form-label">昵称</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" name="nickname" id="nickname" placeholder="请输入nicheng">
                    </div>

                </div>

                <div class="form-group row">
                    <label for="sex" class="col-form-label">性别</label>
                    <div class="col-md-8">
                        <select class="custom-select" name="sex" id="sex">
                            <option value="男">男</option>
                            <option value="女">女</option>
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="age" class="col-form-label">年龄</label>
                    <div class="col-md-8">
                        <input type="number" class="form-control" name="age" id="age">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="email" class="col-form-label">邮箱</label>
                    <div class="col-md-8">
                        <input type="email" class="form-control" name="email" id="email">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="phone" class="col-form-label">电话</label>
                    <div class="col-md-8">
                        <input type="tel" class="form-control" name="phone" id="phone">
                    </div>
                </div>


                <div class="form-group row">
                    <label for="status" class="col-form-label">状态</label>
                    <div class="col-md-8">
                        <select name="status" class="form-control" id="status">
                            <option value="0">正常</option>
                            <option value="1">锁定</option>
                            <option value="2">删除</option>
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <button type="submit" class="btn btn-primary col-md-8">注 册</button>
                </div>
            </form>
        </div>
    </div>
</div>

</body>
</html>